import 'dotenv/config'
const PORT = process.env.PORT
const origin = ["http://localhost:5173"]
const DBURL = process.env.DBURL
const APP_URL = process.env.APP_URL
const REDISDBURL = process.env.REDISDBURL
const VERIFICATION_SIGNATURE = process.env.VERIFICATION_SIGNATURE
const ACCESSSTOKEN_SIGNATURE = process.env.ACCESSSTOKEN_SIGNATURE
const ACCESSSTOKEN_EXPRIE = process.env.ACCESSSTOKEN_EXPRIE
const REFRESHTOKEN_SIGNATURE = process.env.REFRESHTOKEN_SIGNATURE
const REFRESHTOKEN_EXPRIE = process.env.REFRESHTOKEN_EXPRIE
const CLOUD_NAME = process.env.CLOUD_NAME
const CLOUD_API_KEY = process.env.CLOUD_API_KEY
const CLOUD_API_SECRET = process.env.CLOUD_API_SECRET
const ADMIN_DISPLAYNAME = process.env.ADMIN_DISPLAYNAME
const ADMIN_USERNAME = process.env.ADMIN_USERNAME
const ADMIN_EMAIL = process.env.ADMIN_EMAIL
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD
export { PORT, origin, DBURL, VERIFICATION_SIGNATURE, ACCESSSTOKEN_EXPRIE, ACCESSSTOKEN_SIGNATURE, REFRESHTOKEN_EXPRIE, REFRESHTOKEN_SIGNATURE, CLOUD_API_KEY, CLOUD_NAME, CLOUD_API_SECRET, REDISDBURL, APP_URL, ADMIN_DISPLAYNAME, ADMIN_USERNAME, ADMIN_EMAIL, ADMIN_PASSWORD }