import 'dotenv/config'
const PORT = process.env.PORT
const origin = ["http://localhost:5173"]
const DBURL = process.env.DBURL
const VERIFICATION_SIGNATURE = process.env.VERIFICATION_SIGNATURE
const ACCESSSTOKEN_SIGNATURE = process.env.ACCESSSTOKEN_SIGNATURE
const ACCESSSTOKEN_EXPRIE = process.env.ACCESSSTOKEN_EXPRIE
const REFRESHTOKEN_SIGNATURE = process.env.REFRESHTOKEN_SIGNATURE
const REFRESHTOKEN_EXPRIE = process.env.REFRESHTOKEN_EXPRIE
const CLOUD_NAME = process.env.CLOUD_NAME
const CLOUD_API_KEY = process.env.CLOUD_API_KEY
const CLOUD_API_SECRET = process.env.CLOUD_API_SECRET
export { PORT, origin, DBURL, VERIFICATION_SIGNATURE, ACCESSSTOKEN_EXPRIE, ACCESSSTOKEN_SIGNATURE, REFRESHTOKEN_EXPRIE, REFRESHTOKEN_SIGNATURE, CLOUD_API_KEY, CLOUD_NAME, CLOUD_API_SECRET }